/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import model.GeneradorCongruencialMixto;
import model.Modelo;

/**
 *
 * @author Jose
 */
public class OpcionesAvanzadas extends javax.swing.JDialog {

    Modelo modelo;
    GeneradorCongruencialMixto gcm;
    int n;
    
    /**
     * Creates new form OpcionesAvanzadas
     */
    public OpcionesAvanzadas(java.awt.Frame parent, boolean modal, Modelo m) {
        super(parent, modal);
        this.modelo = m;
        this.gcm = m.getGeneradorCongruencialMixto();
        n = gcm.getN();
        initComponents();
        setLocationRelativeTo(null);
        modulo.setText(""+gcm.getM());
        cAditiva.setText(""+gcm.getC());
        cMultiplicativa.setText(""+gcm.getA());
        semilla.setText(""+gcm.getX0());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        semilla = new javax.swing.JTextField();
        modulo = new javax.swing.JTextField();
        cMultiplicativa = new javax.swing.JTextField();
        cAditiva = new javax.swing.JTextField();
        aumentarSemilla = new javax.swing.JButton();
        aumentarCMultiplicativa = new javax.swing.JButton();
        aumentarCAditiva = new javax.swing.JButton();
        reducirSemilla = new javax.swing.JButton();
        reducirCMultiplicativa = new javax.swing.JButton();
        reducirCAditiva = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opciones Avanzadas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Semilla");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Constante multiplicativa");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Constante aditiva");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Modulo");

        semilla.setEditable(false);
        semilla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        modulo.setEditable(false);
        modulo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        modulo.setText("365");

        cMultiplicativa.setEditable(false);
        cMultiplicativa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cAditiva.setEditable(false);
        cAditiva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        aumentarSemilla.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        aumentarSemilla.setText("+");
        aumentarSemilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aumentarSemillaMouseClicked(evt);
            }
        });

        aumentarCMultiplicativa.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        aumentarCMultiplicativa.setText("+");
        aumentarCMultiplicativa.setPreferredSize(new java.awt.Dimension(54, 30));
        aumentarCMultiplicativa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aumentarCMultiplicativaMouseClicked(evt);
            }
        });

        aumentarCAditiva.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        aumentarCAditiva.setText("+");
        aumentarCAditiva.setPreferredSize(new java.awt.Dimension(54, 30));
        aumentarCAditiva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aumentarCAditivaMouseClicked(evt);
            }
        });

        reducirSemilla.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        reducirSemilla.setText("-");
        reducirSemilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reducirSemillaMouseClicked(evt);
            }
        });

        reducirCMultiplicativa.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        reducirCMultiplicativa.setText("-");
        reducirCMultiplicativa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reducirCMultiplicativaMouseClicked(evt);
            }
        });

        reducirCAditiva.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        reducirCAditiva.setText("-");
        reducirCAditiva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reducirCAditivaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(semilla)
                            .addComponent(modulo, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(cMultiplicativa)
                            .addComponent(cAditiva))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aumentarCMultiplicativa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(aumentarSemilla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aumentarCAditiva, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(reducirCMultiplicativa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(reducirSemilla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reducirCAditiva, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(semilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aumentarSemilla)
                    .addComponent(reducirSemilla))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cMultiplicativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(reducirCMultiplicativa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(aumentarCMultiplicativa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cAditiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aumentarCAditiva, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reducirCAditiva))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(modulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Variables del generador congruencial mixto");

        aceptar.setText("Aceptar");
        aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarMouseClicked(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar)
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aumentarSemillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aumentarSemillaMouseClicked
        int valor = Integer.parseInt(semilla.getText());
        valor++;
        semilla.setText(""+valor);
    }//GEN-LAST:event_aumentarSemillaMouseClicked

    private void reducirSemillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reducirSemillaMouseClicked
        int valor = Integer.parseInt(semilla.getText());
        if(valor > 1){
            valor--;
            semilla.setText(""+valor);
        }
    }//GEN-LAST:event_reducirSemillaMouseClicked

    private void aumentarCMultiplicativaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aumentarCMultiplicativaMouseClicked
        n++;
        cMultiplicativa.setText(""+((365*n)+1));
    }//GEN-LAST:event_aumentarCMultiplicativaMouseClicked

    private void reducirCMultiplicativaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reducirCMultiplicativaMouseClicked
        if(n > 1){
            n--;
            cMultiplicativa.setText(""+((365*n)+1));
        }           
    }//GEN-LAST:event_reducirCMultiplicativaMouseClicked

    private void aumentarCAditivaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aumentarCAditivaMouseClicked
        int valor = Integer.parseInt(cAditiva.getText());
        valor++;
        while(valor % 5 == 0 || valor % 73 == 0){
            valor++;
        }
        cAditiva.setText(""+valor);
    }//GEN-LAST:event_aumentarCAditivaMouseClicked

    private void reducirCAditivaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reducirCAditivaMouseClicked
        int valor = Integer.parseInt(cAditiva.getText());
        if(valor > 2){
            valor--;
            while(valor % 5 == 0 || valor % 73 == 0){
                valor--;
            }
            cAditiva.setText(""+valor);
        }
    }//GEN-LAST:event_reducirCAditivaMouseClicked

    private void aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMouseClicked
        int x0 = Integer.parseInt(semilla.getText());
        int a = Integer.parseInt(cMultiplicativa.getText());
        int c = Integer.parseInt(cAditiva.getText());
        int m = 365;
        modelo.getGeneradorCongruencialMixto().setN(n);
        modelo.getGeneradorCongruencialMixto().asignarValores(a, c, m, x0);
        this.dispose();
    }//GEN-LAST:event_aceptarMouseClicked

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton aumentarCAditiva;
    private javax.swing.JButton aumentarCMultiplicativa;
    private javax.swing.JButton aumentarSemilla;
    private javax.swing.JTextField cAditiva;
    private javax.swing.JTextField cMultiplicativa;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField modulo;
    private javax.swing.JButton reducirCAditiva;
    private javax.swing.JButton reducirCMultiplicativa;
    private javax.swing.JButton reducirSemilla;
    private javax.swing.JTextField semilla;
    // End of variables declaration//GEN-END:variables
}
