/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import model.GeneradorCongruencialMixto;
import model.Modelo;

/**
 *
 * @author Jose
 */
public class OpcionesAvanzadas extends javax.swing.JDialog {

    Modelo modelo;
    GeneradorCongruencialMixto gcm;
    int n;
    
    /**
     * Creates new form OpcionesAvanzadas
     */
    public OpcionesAvanzadas(java.awt.Frame parent, boolean modal, Modelo m) {
        super(parent, modal);
        this.modelo = m;
        this.gcm = m.getGeneradorCongruencialMixto();
        n = gcm.getN();
        initComponents();
        modulo.setText(""+gcm.getM());
        cAditiva.setText(""+gcm.getC());
        cMultiplicativa.setText(""+gcm.getA());
        semilla.setText(""+gcm.getX0());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        semilla = new javax.swing.JTextField();
        modulo = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cMultiplicativa = new javax.swing.JTextField();
        cAditiva = new javax.swing.JTextField();
        aumentarSemilla = new javax.swing.JButton();
        aumentarCMultiplicativa = new javax.swing.JButton();
        aumentarCAditiva = new javax.swing.JButton();
        reducirSemilla = new javax.swing.JButton();
        reducirCMultiplicativa = new javax.swing.JButton();
        reducirCAditiva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Opciones Avanzadas");

        jLabel2.setText("Semilla");

        jLabel3.setText("Constante multiplicativa");

        jLabel4.setText("Constante aditiva");

        jLabel5.setText("Modulo");

        semilla.setEditable(false);
        semilla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        modulo.setEditable(false);
        modulo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        modulo.setText("365");

        cancelar.setText("Calcelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarMouseClicked(evt);
            }
        });

        jLabel7.setText("Variables del generador congruencial mixto");

        cMultiplicativa.setEditable(false);
        cMultiplicativa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cAditiva.setEditable(false);
        cAditiva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        aumentarSemilla.setText("+");
        aumentarSemilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aumentarSemillaMouseClicked(evt);
            }
        });

        aumentarCMultiplicativa.setText("+");
        aumentarCMultiplicativa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aumentarCMultiplicativaMouseClicked(evt);
            }
        });

        aumentarCAditiva.setText("+");
        aumentarCAditiva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aumentarCAditivaMouseClicked(evt);
            }
        });

        reducirSemilla.setText("-");
        reducirSemilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reducirSemillaMouseClicked(evt);
            }
        });

        reducirCMultiplicativa.setText("-");
        reducirCMultiplicativa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reducirCMultiplicativaMouseClicked(evt);
            }
        });

        reducirCAditiva.setText("-");
        reducirCAditiva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reducirCAditivaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(semilla)
                                    .addComponent(modulo, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(cMultiplicativa)
                                    .addComponent(cAditiva))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aumentarCMultiplicativa, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(aumentarSemilla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aumentarCAditiva, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(reducirCMultiplicativa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(reducirSemilla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reducirCAditiva, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(semilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aumentarSemilla)
                    .addComponent(reducirSemilla))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cMultiplicativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aumentarCMultiplicativa)
                    .addComponent(reducirCMultiplicativa))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cAditiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aumentarCAditiva)
                    .addComponent(reducirCAditiva))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(modulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(aceptar))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aumentarSemillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aumentarSemillaMouseClicked
        int valor = Integer.parseInt(semilla.getText());
        valor++;
        semilla.setText(""+valor);
    }//GEN-LAST:event_aumentarSemillaMouseClicked

    private void reducirSemillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reducirSemillaMouseClicked
        int valor = Integer.parseInt(semilla.getText());
        if(valor > 1){
            valor--;
            semilla.setText(""+valor);
        }
    }//GEN-LAST:event_reducirSemillaMouseClicked

    private void aumentarCMultiplicativaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aumentarCMultiplicativaMouseClicked
        n++;
        cMultiplicativa.setText(""+((365*n)+1));
    }//GEN-LAST:event_aumentarCMultiplicativaMouseClicked

    private void reducirCMultiplicativaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reducirCMultiplicativaMouseClicked
        if(n > 1){
            n--;
            cMultiplicativa.setText(""+((365*n)+1));
        }           
    }//GEN-LAST:event_reducirCMultiplicativaMouseClicked

    private void aumentarCAditivaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aumentarCAditivaMouseClicked
        int valor = Integer.parseInt(cAditiva.getText());
        valor++;
        while(valor % 5 == 0 || valor % 73 == 0){
            valor++;
        }
        cAditiva.setText(""+valor);
    }//GEN-LAST:event_aumentarCAditivaMouseClicked

    private void reducirCAditivaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reducirCAditivaMouseClicked
        int valor = Integer.parseInt(cAditiva.getText());
        if(valor > 2){
            valor--;
            while(valor % 5 == 0 || valor % 73 == 0){
                valor--;
            }
            cAditiva.setText(""+valor);
        }
    }//GEN-LAST:event_reducirCAditivaMouseClicked

    private void aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMouseClicked
        int x0 = Integer.parseInt(semilla.getText());
        int a = Integer.parseInt(cMultiplicativa.getText());
        int c = Integer.parseInt(cAditiva.getText());
        int m = 365;
        modelo.getGeneradorCongruencialMixto().setN(n);
        modelo.getGeneradorCongruencialMixto().asignarValores(a, c, m, x0);
        this.dispose();
    }//GEN-LAST:event_aceptarMouseClicked

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton aumentarCAditiva;
    private javax.swing.JButton aumentarCMultiplicativa;
    private javax.swing.JButton aumentarSemilla;
    private javax.swing.JTextField cAditiva;
    private javax.swing.JTextField cMultiplicativa;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField modulo;
    private javax.swing.JButton reducirCAditiva;
    private javax.swing.JButton reducirCMultiplicativa;
    private javax.swing.JButton reducirSemilla;
    private javax.swing.JTextField semilla;
    // End of variables declaration//GEN-END:variables
}
