/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.Controlador;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.*;
import com.jtattoo.plaf.*;

/**
 *
 * @author User
 */
public class Simulador extends javax.swing.JFrame {
    
    // Simulation model constants
    final int MEJOR_HABITACIONES = 1;
    final int MEJOR_PRECIO = 2;
    final int MEJOR_COMBINACION = 3;
    
    // Simulation state constants
    final int DETENIDO = 4;
    final int EN_EJECUCION = 5;
    final int PAUSADO = 6;
    
    TablaCombinado tc;
    TablaVariacionPrecios tvp;
    TablaMejorIncremento tmi;
    Controlador c;
    /**
     * Creates new form Simulador
     */
    public Simulador(Controlador c) {
        try{
          UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
        }
        catch(Exception e){}
        initComponents();
        this.c=c;
        this.setLocationRelativeTo(null);
        cambiarModeloJMenuItem.addMouseListener(c);
        cambiarDatoJMenuItem.addMouseListener(c);
        pieChartJButton.addMouseListener(c);
        resultadosJButton.addMouseListener(c);
        playJButton.addMouseListener(c);
        printJButton.addMouseListener(c);
        graficoJButton.addMouseListener(c);
        mejorOpJButton.addMouseListener(c);
        resultadosJButton.setEnabled(false);
        graficoJButton.setEnabled(false);
        jSlider1.addChangeListener(c);
        tc = new TablaCombinado();
        tvp = new TablaVariacionPrecios();
        tmi = new TablaMejorIncremento(); // Create a hidden TablaMejorIncremento
    }
    
    // Show window elements according to choosen option
    public void mostrarOpcion(int op) {
        switch(op) {
            case MEJOR_HABITACIONES: tipoJLabel.setText("Mejor cantidad de habitaciones"); break;
            case MEJOR_PRECIO: tipoJLabel.setText("Mejor precio de habitaciones"); break;
            case MEJOR_COMBINACION: tipoJLabel.setText("Mejor combinación: precio y habitaciones"); break;
        }
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pieChartJButton = new javax.swing.JButton();
        mejorOpJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        firstJButton = new javax.swing.JButton();
        playJButton = new javax.swing.JButton();
        lastJButton = new javax.swing.JButton();
        pauseJButton = new javax.swing.JButton();
        stopJButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        resultadosJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tipoJLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        tipoJLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tipoJLabel2 = new javax.swing.JLabel();
        graficoJButton = new javax.swing.JButton();
        chartComboBox = new javax.swing.JComboBox();
        printJButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoJMenu = new javax.swing.JMenu();
        nuevoJMenuItem = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        simulacionJMenu = new javax.swing.JMenu();
        cambiarModeloJMenuItem = new javax.swing.JMenuItem();
        cambiarDatoJMenuItem = new javax.swing.JMenuItem();
        ayudaJMenu = new javax.swing.JMenu();
        manualJMenuItem = new javax.swing.JMenuItem();
        acercaDeJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Diplomat");
        setResizable(false);

        jPanel.setBackground(new java.awt.Color(0, 0, 51));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ani_background.png"))); // NOI18N

        pieChartJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pieChart.png"))); // NOI18N
        pieChartJButton.setBorder(null);

        mejorOpJButton.setBackground(new java.awt.Color(0, 0, 0));
        mejorOpJButton.setForeground(new java.awt.Color(255, 255, 255));
        mejorOpJButton.setText("Mejor Opcion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(mejorOpJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pieChartJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pieChartJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(mejorOpJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Velocidad de la Simulación");

        jSlider1.setBackground(new java.awt.Color(0, 0, 51));
        jSlider1.setMaximum(1000);
        jSlider1.setMinimum(10);
        jSlider1.setValue(500);

        firstJButton.setBackground(new java.awt.Color(0, 0, 51));
        firstJButton.setForeground(new java.awt.Color(0, 0, 51));
        firstJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/first.png"))); // NOI18N
        firstJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        playJButton.setBackground(new java.awt.Color(0, 0, 51));
        playJButton.setForeground(new java.awt.Color(0, 0, 51));
        playJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        playJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lastJButton.setBackground(new java.awt.Color(0, 0, 51));
        lastJButton.setForeground(new java.awt.Color(0, 0, 51));
        lastJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/last.png"))); // NOI18N
        lastJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pauseJButton.setBackground(new java.awt.Color(0, 0, 51));
        pauseJButton.setForeground(new java.awt.Color(0, 0, 51));
        pauseJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pause.png"))); // NOI18N
        pauseJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        stopJButton.setBackground(new java.awt.Color(0, 0, 51));
        stopJButton.setForeground(new java.awt.Color(0, 0, 51));
        stopJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stop.png"))); // NOI18N
        stopJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("ESTADO DE LA SIMULACIÓN");

        resultadosJButton.setText("Ver resultados");
        resultadosJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadosJButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Opción elegida:");

        tipoJLabel.setForeground(new java.awt.Color(0, 0, 51));
        tipoJLabel.setText("0");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setForeground(new java.awt.Color(204, 204, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 102));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Velocidad actual:");

        tipoJLabel1.setForeground(new java.awt.Color(0, 0, 51));
        tipoJLabel1.setText("500 ms/día");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Estado de la Simulación:");

        tipoJLabel2.setForeground(new java.awt.Color(0, 0, 51));
        tipoJLabel2.setText("Detenido");

        graficoJButton.setText("Grafico");

        chartComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Barras", "Doble Eje" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(chartComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(graficoJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultadosJButton)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoJLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipoJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipoJLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tipoJLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultadosJButton)
                    .addComponent(graficoJButton)
                    .addComponent(chartComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        printJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/printer.png"))); // NOI18N

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(firstJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pauseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(stopJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pauseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        archivoJMenu.setLabel("Archivo");

        nuevoJMenuItem.setLabel("Nuevo");
        nuevoJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoJMenuItemActionPerformed(evt);
            }
        });
        archivoJMenu.add(nuevoJMenuItem);

        jMenuItem2.setText("Abrir...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        archivoJMenu.add(jMenuItem2);

        jMenuItem3.setText("Guardar...");
        archivoJMenu.add(jMenuItem3);

        jMenuItem4.setText("Imprimir...");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        archivoJMenu.add(jMenuItem4);

        jMenuItem5.setText("Cerrar");
        archivoJMenu.add(jMenuItem5);

        jMenuBar1.add(archivoJMenu);

        simulacionJMenu.setText("Simulación");
        simulacionJMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                simulacionJMenuMousePressed(evt);
            }
        });

        cambiarModeloJMenuItem.setText("Cambiar Modelo");
        cambiarModeloJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarModeloJMenuItemActionPerformed(evt);
            }
        });
        simulacionJMenu.add(cambiarModeloJMenuItem);

        cambiarDatoJMenuItem.setText("Cambiar Datos");
        cambiarDatoJMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cambiarDatoJMenuItemMousePressed(evt);
            }
        });
        simulacionJMenu.add(cambiarDatoJMenuItem);

        jMenuBar1.add(simulacionJMenu);

        ayudaJMenu.setText("Ayuda");

        manualJMenuItem.setText("Manual de Usuario");
        ayudaJMenu.add(manualJMenuItem);

        acercaDeJMenuItem.setText("Acerca de...");
        acercaDeJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaDeJMenuItemActionPerformed(evt);
            }
        });
        ayudaJMenu.add(acercaDeJMenuItem);

        jMenuBar1.add(ayudaJMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoJMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoJMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evjPanel//GEN-FIRST:event_jMenuItem4ActionPerformed
    ){
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void resultadosJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadosJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadosJButtonActionPerformed

    private void acercaDeJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDeJMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acercaDeJMenuItemActionPerformed

    private void simulacionJMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simulacionJMenuMousePressed

    }//GEN-LAST:event_simulacionJMenuMousePressed

    private void cambiarDatoJMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarDatoJMenuItemMousePressed

    }//GEN-LAST:event_cambiarDatoJMenuItemMousePressed

    private void cambiarModeloJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarModeloJMenuItemActionPerformed

    }//GEN-LAST:event_cambiarModeloJMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acercaDeJMenuItem;
    private javax.swing.JMenu archivoJMenu;
    private javax.swing.JMenu ayudaJMenu;
    private javax.swing.JMenuItem cambiarDatoJMenuItem;
    private javax.swing.JMenuItem cambiarModeloJMenuItem;
    private javax.swing.JComboBox chartComboBox;
    private javax.swing.JButton firstJButton;
    private javax.swing.JButton graficoJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton lastJButton;
    private javax.swing.JMenuItem manualJMenuItem;
    private javax.swing.JButton mejorOpJButton;
    private javax.swing.JMenuItem nuevoJMenuItem;
    private javax.swing.JButton pauseJButton;
    private javax.swing.JButton pieChartJButton;
    private javax.swing.JButton playJButton;
    private javax.swing.JButton printJButton;
    private javax.swing.JButton resultadosJButton;
    private javax.swing.JMenu simulacionJMenu;
    private javax.swing.JButton stopJButton;
    private javax.swing.JLabel tipoJLabel;
    private javax.swing.JLabel tipoJLabel1;
    private javax.swing.JLabel tipoJLabel2;
    // End of variables declaration//GEN-END:variables

   public JButton getJBVerResultados(){
        return resultadosJButton;
    }
    
    public JButton getJBPlay(){
        return playJButton;
    }
    public JButton getJBGrafico(){
        return graficoJButton;
    }
    public JButton getPieChart()
    {
        return pieChartJButton;
    }
    public JButton getPrintJButton()
    {
        return printJButton;
    }
    public JButton getMejorOpcionJButton()
    {
        return mejorOpJButton;
    }
    public JComboBox getChartComboBox()
    {
        return chartComboBox;
    }
    public void setTablaVariacionPrecios(TablaVariacionPrecios t){
        this.tvp = t;
    }

    public TablaVariacionPrecios getTablaVariacionPrecios() {
        return tvp;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }
    
    public void setTablaMejorIncremento(TablaMejorIncremento t){
        this.tmi = t;
    }
    
    public TablaMejorIncremento getTablaMejorIncremento(){
        return tmi;
    }
    
    public JMenuItem getCambiarModeloJMenuItem()
    {
        return cambiarModeloJMenuItem;
    }
    public JMenuItem getCambiarDatoJMenuItem()
    {
        return cambiarDatoJMenuItem;
    }
   
    public void cleanTextArea1() {
        jTextArea1.setText("");
    }
    public void disableButton()
    {
        resultadosJButton.setEnabled(false);
        graficoJButton.setEnabled(false);
        printJButton.setEnabled(false);
    }
    
    // Sets speed text to delay value
    public void setSpeed(int delay) {
        tipoJLabel1.setText(delay + " ms/día");
    }
    
    // Sends results table from Controller to adecuate table frame and show
    public void mostrarResultados(Object[][] tabla, int op) {
        switch(op) {
            case 1: tmi.mostrar(tabla); break;
            case 2: tvp.mostrar(tabla); break;
            case 3: tc.mostrar(tabla); break;
        }
    }
    
    // Enables results button and shows result text
    public void enableResults(boolean b, String s) {
        resultadosJButton.setEnabled(b);
        jTextArea1.setText(s);
    }
    
    // Sets interface elements to match current simulation state
    public void setSimState(int st) {
        switch(st) {
            case DETENIDO:
                tipoJLabel2.setText("Detenido");
                break;
            case EN_EJECUCION:
                tipoJLabel2.setText("En ejecución");
                break;
        }
    }






}
